### ISSUE TITLE
yield generates junk in output stream

### ISSUE THREAD

**Issue by dux** [hamlit/hamlit-block#3]
Error in 0.4.0, 0.3.1 works fine

This code should render only  'IGNORE MENU'

```
def menu(kind=:ul, opts={})
  nav = UiPrimerMenu.new(kind, opts)
  nav.render yield nav
  'IGNORE MENU'
end
```

or 

```
def menu(kind=:ul, opts={}, &block)
  nav = UiPrimerMenu.new(kind, opts)
  nav.render block.call(nav)
  'IGNORE MENU'
end
```

but it renders a junk in output stream and the final result is this

https://i.imgur.com/SHST6zI.png

**Comment by k0kubun** [comment]
I'm sorry but there are too few contexts to understand. At least I couldn't guess what is `UiPrimerMenu#render`'s implementation and what kind of block is given. Could you provide reproductive gist, repository or simple snippets which can executed on my environment?

**Comment by k0kubun** [comment]
And I don't know well about cells, which you may use because you use hamlit-block. If you use hamlit-block on that environment, I'll ask some help for its maintainers...

**Comment by dux** [comment]
sorry, I will give as simple as possible example

this hamlit template

```
    %hr
    = hamlit_test do
      foo
    %hr

```

with this code in helper

```
  def hamlit_test
    yield
  end
```

produces this

https://i.imgur.com/dFW3KBW.png

instead of this

https://i.imgur.com/hB5PSgt.png

I have to say I use pure rack without rails. I will try to clone the code and run tests, did not do that.

**Comment by dux** [comment]
test pass for for ruby 2.3.3 and ruby 2.4.0

6 examples, 0 failures

I am using Tilt gem, this is how i register it

```
Tilt.register Hamlit::Template, 'haml'
```

**Comment by k0kubun** [comment]
I made https://github.com/k0kubun/misc/tree/hamlit-block. With https://github.com/k0kubun/misc/commit/5eb1069788a12660bf0f1fce8c4c8c6d335e0b67, it renders:

```
<hr>
foo
<hr>
foo
<hr>
```

<hr>

As you can see, it renders strangely. That's because hamlit-block is NOT designed to support capturing by yield for normal Rails environment. You can use Rails's `capture` helper instead. Because it works, Hamlit and hamlit-block don't support that. hamlit-block is created for cells because its capturing is not implemented like Rails.

**Comment by dux** [comment]
I am not using Rails, using plain rack with Tilt gem. I will try to remove Tilt and see what happens.

**Comment by dux** [comment]
> hamlit-block is created for cells because its capturing is not implemented like Rails.

ok, all good, but is there some error in my code? all works well with v0.3.1. I love hamlit and removal of capture. it is good and right approach.

**Comment by k0kubun** [comment]
Ahhh... so, okay, it's very unexpected case for Hamlit and hamlit-block. Waiting for your reproductive code.

<hr>

Very important point: hamlit-block v0.4.0 doesn't modify `Hamlit::Engine` and just adds `Hamlit::Block::Engine`. And `Hamlit::Template` uses `Hamlit::Engine`. Some fixes are required. Maybe having `Hamlit::Block::Template`.

**Comment by dux** [comment]
```
Maybe having Hamlit::Block::Template
```

?

**Comment by k0kubun** [comment]
I'll implement `Hamlit::Block::Template` later. After that, you do `Tilt.register Hamlit::Block::Template, 'haml'`.

I'm busy for an hour. Just a moment please.

**Comment by dux** [comment]
wont work

```
Using hamlit 2.7.5
Using hamlit-block 0.4.0


! Unable to load application: NameError: uninitialized constant Hamlit::Block::Template
Did you mean?  Hamlit::Template
               Temple
config.ru:4:in `eval': uninitialized constant Hamlit::Block::Template (NameError)
Did you mean?  Hamlit::Template
               Temple
```

**Comment by k0kubun** [comment]
> I'll implement Hamlit::Block::Template later.

**Comment by dux** [comment]
and also, minimal code required to compile template and run it, without Tilt, would be useful in readme

thx for great work

**Comment by k0kubun** [comment]
Shipped `Hamlit::Block::Template` and automatic registration as hamlit-block v0.5.0. Could you try this?

**Comment by dux** [comment]
bravisimo ;)

works, no junk, but engine has to be switched. with Hamlit::Template is not working.

```
# Tilt.register Hamlit::Template, 'haml'
Tilt.register Hamlit::Block::Template, 'haml'
```
